#!/usr/bin/env python3
"""Batch-convert AutoLabSim NPZ episodes to LeRobotDataset v3 for ACT.

Tested against the LeRobot 0.4.4 public API.

Default source layout::

    data/episodes/screw_cap_batch/
      episode_000_seed_0000/
        episode.npz
        metadata.json
      episode_001_seed_0001/
        episode.npz
        metadata.json

Default output::

    data/lerobot/act/

The current AutoLabSim recorder stores the action together with the observation
obtained after executing that action. Therefore, the default alignment is:

    observation[t] -> action[t + 1]

Set ``--action-offset 0`` only after changing the recorder to save the
pre-action observation.
"""

from __future__ import annotations

import argparse
import gc
import importlib.metadata
import json
import shutil
import sys
import tempfile
import zipfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np


DEFAULT_CAMERAS = (
    "image_overview_camera",
    "image_wrist_cam",
    "image_wrist_cam1",
)

TASK_TEXT_MAP = {
    "bimanual_unscrew_cap": (
        "Use both robot arms to hold the centrifuge tube and unscrew its cap."
    ),
}


@dataclass(frozen=True)
class ArrayHeader:
    shape: tuple[int, ...]
    dtype: str
    fortran_order: bool


@dataclass
class EpisodeRecord:
    source_dir: str
    npz_path: str
    metadata_path: str
    source_episode_index: int | None
    reset_seed: int | None
    source_task: str
    task_text: str
    success: bool | None
    raw_frames: int
    converted_frames: int


class ConversionError(RuntimeError):
    """Raised when source data are incompatible with the requested conversion."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert AutoLabSim batch episodes to LeRobot v3 for ACT."
    )
    parser.add_argument(
        "--input-root",
        type=Path,
        default=Path("data/episodes/screw_cap_batch"),
        help="Directory containing episode_* subdirectories.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("data/lerobot/act"),
        help="Destination LeRobot dataset root.",
    )
    parser.add_argument(
        "--repo-id",
        default="local/autolabsim_screw_cap_act",
        help="LeRobot repository identifier stored in dataset metadata.",
    )
    parser.add_argument(
        "--robot-type",
        default="autolabsim_dual_ur5e",
        help="Robot type stored in LeRobot metadata.",
    )
    parser.add_argument(
        "--state-key",
        default="ctrl",
        choices=("ctrl", "qpos", "state"),
        help="NPZ key used as observation.state. Default: ctrl.",
    )
    parser.add_argument(
        "--action-key",
        default="action",
        help="NPZ key used as the action source.",
    )
    parser.add_argument(
        "--action-offset",
        type=int,
        default=1,
        choices=(0, 1),
        help="Use action[t + offset] for observation[t]. Default: 1.",
    )
    parser.add_argument(
        "--cameras",
        default=",".join(DEFAULT_CAMERAS),
        help=(
            "Comma-separated NPZ image keys. Output keys are generated by "
            "removing the leading 'image_'."
        ),
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=None,
        help="Dataset FPS. If omitted, infer it from the first episode time array.",
    )
    parser.add_argument(
        "--task-text",
        default=None,
        help="Override the natural-language task for every episode.",
    )
    parser.add_argument(
        "--require-success",
        action="store_true",
        help=(
            "Only convert episodes explicitly marked successful. For this task, "
            "metadata.screw_progress.released is used when available."
        ),
    )
    parser.add_argument(
        "--skip-invalid",
        action="store_true",
        help="Skip malformed/incompatible episodes instead of stopping.",
    )
    parser.add_argument(
        "--max-episodes",
        type=int,
        default=None,
        help="Convert at most this many valid episodes; useful for smoke tests.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Delete output-root before conversion if it already exists.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Scan and validate inputs without writing a LeRobot dataset.",
    )
    parser.add_argument(
        "--in-memory",
        action="store_true",
        help=(
            "Load all camera arrays of one episode into RAM. By default, camera "
            "arrays are staged as temporary .npy memmaps to reduce peak RAM use."
        ),
    )
    parser.add_argument(
        "--temp-root",
        type=Path,
        default=None,
        help=(
            "Directory for temporary camera memmaps. Default: a hidden directory "
            "beside output-root. Ensure sufficient free disk space."
        ),
    )
    parser.add_argument(
        "--resize-height",
        type=int,
        default=None,
        help="Optional output image height. Must be used with --resize-width.",
    )
    parser.add_argument(
        "--resize-width",
        type=int,
        default=None,
        help="Optional output image width. Must be used with --resize-height.",
    )
    parser.add_argument(
        "--vcodec",
        default="h264",
        choices=("h264", "hevc", "libsvtav1", "auto"),
        help="Video codec passed to LeRobot. Default: h264.",
    )
    parser.add_argument(
        "--image-writer-threads",
        type=int,
        default=4,
        help="LeRobot asynchronous image-writer threads. Default: 4.",
    )
    parser.add_argument(
        "--no-parallel-encoding",
        action="store_true",
        help="Encode camera videos sequentially instead of in parallel.",
    )
    parser.add_argument(
        "--skip-verify",
        action="store_true",
        help="Do not reload and sample the completed LeRobot dataset.",
    )
    return parser.parse_args()


def parse_cameras(value: str) -> tuple[str, ...]:
    cameras = tuple(item.strip() for item in value.split(",") if item.strip())
    if not cameras:
        raise ConversionError("At least one camera key is required.")
    if len(set(cameras)) != len(cameras):
        raise ConversionError(f"Duplicate camera keys: {cameras}")
    return cameras


def output_camera_key(source_key: str) -> str:
    name = source_key.removeprefix("image_")
    if not name:
        raise ConversionError(f"Invalid camera key: {source_key!r}")
    return f"observation.images.{name}"


def read_array_header(npz_path: Path, key: str) -> ArrayHeader:
    member = f"{key}.npy"
    try:
        with zipfile.ZipFile(npz_path) as archive:
            with archive.open(member) as stream:
                version = np.lib.format.read_magic(stream)
                if version == (1, 0):
                    shape, fortran_order, dtype = np.lib.format.read_array_header_1_0(stream)
                elif version == (2, 0):
                    shape, fortran_order, dtype = np.lib.format.read_array_header_2_0(stream)
                else:
                    # NPY v3 uses UTF-8 headers. NumPy 1.x and 2.x expose the
                    # generic reader from different internal modules.
                    reader = getattr(np.lib.format, "_read_array_header", None)
                    if reader is None:
                        try:
                            from numpy.lib import _format_impl

                            reader = _format_impl._read_array_header
                        except (ImportError, AttributeError) as exc:
                            raise ConversionError(
                                f"Unsupported NPY header version {version} in {npz_path}"
                            ) from exc
                    shape, fortran_order, dtype = reader(stream, version)
    except KeyError as exc:
        raise ConversionError(f"{npz_path}: missing NPZ key {key!r}") from exc
    except (OSError, ValueError, zipfile.BadZipFile) as exc:
        raise ConversionError(f"Cannot read {key!r} header from {npz_path}: {exc}") from exc

    return ArrayHeader(
        shape=tuple(int(v) for v in shape),
        dtype=np.dtype(dtype).str,
        fortran_order=bool(fortran_order),
    )


def load_metadata(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            value = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        raise ConversionError(f"Cannot read metadata {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ConversionError(f"Metadata must be a JSON object: {path}")
    return value


def infer_success(metadata: dict[str, Any]) -> bool | None:
    for key in ("success", "task_success", "completed"):
        value = metadata.get(key)
        if isinstance(value, bool):
            return value

    screw_progress = metadata.get("screw_progress")
    if isinstance(screw_progress, dict):
        released = screw_progress.get("released")
        if isinstance(released, bool):
            return released

    return None


def task_to_text(source_task: str, override: str | None) -> str:
    if override:
        return override.strip()
    if source_task in TASK_TEXT_MAP:
        return TASK_TEXT_MAP[source_task]
    return source_task.replace("_", " ").strip().capitalize() + "."


def infer_fps(npz_path: Path) -> int:
    try:
        with np.load(npz_path, allow_pickle=False) as data:
            if "time" not in data.files:
                raise ConversionError(
                    f"{npz_path}: no 'time' key; provide --fps explicitly."
                )
            timestamps = np.asarray(data["time"], dtype=np.float64)
    except (OSError, ValueError) as exc:
        raise ConversionError(f"Cannot load timestamps from {npz_path}: {exc}") from exc

    if timestamps.ndim != 1 or timestamps.size < 2:
        raise ConversionError(f"{npz_path}: invalid time array shape {timestamps.shape}")
    deltas = np.diff(timestamps)
    if not np.isfinite(deltas).all() or np.any(deltas <= 0):
        raise ConversionError(f"{npz_path}: timestamps are not strictly increasing")

    median_dt = float(np.median(deltas))
    fps_float = 1.0 / median_dt
    fps = int(round(fps_float))
    if fps <= 0 or abs(fps_float - fps) > 1e-3:
        raise ConversionError(
            f"{npz_path}: inferred non-integer FPS {fps_float:.6f}; provide --fps."
        )
    tolerance = max(1e-6, median_dt * 1e-3)
    if not np.allclose(deltas, median_dt, rtol=0.0, atol=tolerance):
        raise ConversionError(
            f"{npz_path}: non-uniform timestamps; median dt={median_dt:.9f}."
        )
    return fps


def validate_resize(args: argparse.Namespace) -> tuple[int, int] | None:
    h, w = args.resize_height, args.resize_width
    if (h is None) != (w is None):
        raise ConversionError(
            "--resize-height and --resize-width must be specified together."
        )
    if h is None:
        return None
    if h <= 0 or w <= 0:
        raise ConversionError("Resize dimensions must be positive.")
    return int(h), int(w)


def discover_episode_dirs(input_root: Path) -> list[Path]:
    if not input_root.is_dir():
        raise ConversionError(f"Input directory does not exist: {input_root}")
    dirs = sorted(path for path in input_root.glob("episode_*") if path.is_dir())
    if not dirs:
        raise ConversionError(f"No episode_* directories found under {input_root}")
    return dirs


def scan_episodes(
    args: argparse.Namespace,
    cameras: tuple[str, ...],
    resize: tuple[int, int] | None,
) -> tuple[list[EpisodeRecord], dict[str, ArrayHeader], int]:
    records: list[EpisodeRecord] = []
    reference_headers: dict[str, ArrayHeader] = {}
    inferred_fps: int | None = args.fps
    episode_dirs = discover_episode_dirs(args.input_root)

    for episode_dir in episode_dirs:
        npz_path = episode_dir / "episode.npz"
        metadata_path = episode_dir / "metadata.json"
        try:
            if not npz_path.is_file():
                raise ConversionError(f"Missing file: {npz_path}")
            if not metadata_path.is_file():
                raise ConversionError(f"Missing file: {metadata_path}")

            metadata = load_metadata(metadata_path)
            success = infer_success(metadata)
            if args.require_success and success is not True:
                print(
                    f"[skip] {episode_dir.name}: success={success!r}, "
                    "but --require-success was specified"
                )
                continue

            keys = (args.state_key, args.action_key, *cameras)
            headers = {key: read_array_header(npz_path, key) for key in keys}

            state_header = headers[args.state_key]
            action_header = headers[args.action_key]
            if len(state_header.shape) != 2:
                raise ConversionError(
                    f"{npz_path}: {args.state_key} must be 2-D, got {state_header.shape}"
                )
            if len(action_header.shape) != 2:
                raise ConversionError(
                    f"{npz_path}: {args.action_key} must be 2-D, got {action_header.shape}"
                )

            raw_frames = action_header.shape[0]
            lengths = {
                args.state_key: state_header.shape[0],
                args.action_key: action_header.shape[0],
            }
            for camera in cameras:
                header = headers[camera]
                if len(header.shape) != 4 or header.shape[-1] not in (1, 3, 4):
                    raise ConversionError(
                        f"{npz_path}: {camera} must have shape (T,H,W,C), got {header.shape}"
                    )
                if np.dtype(header.dtype) != np.uint8:
                    raise ConversionError(
                        f"{npz_path}: {camera} must be uint8, got {header.dtype}"
                    )
                lengths[camera] = header.shape[0]

            if len(set(lengths.values())) != 1:
                raise ConversionError(
                    f"{npz_path}: frame count mismatch: {lengths}"
                )
            converted_frames = raw_frames - args.action_offset
            if converted_frames <= 0:
                raise ConversionError(
                    f"{npz_path}: not enough frames for action offset {args.action_offset}"
                )

            if inferred_fps is None:
                inferred_fps = infer_fps(npz_path)

            if reference_headers:
                for key in keys:
                    current = headers[key]
                    reference = reference_headers[key]
                    current_shape = current.shape[1:] if key in cameras else current.shape[1:]
                    reference_shape = reference.shape[1:] if key in cameras else reference.shape[1:]
                    if current_shape != reference_shape or current.dtype != reference.dtype:
                        raise ConversionError(
                            f"{npz_path}: feature {key!r} differs from first episode: "
                            f"shape {current_shape} vs {reference_shape}, "
                            f"dtype {current.dtype} vs {reference.dtype}"
                        )
            else:
                reference_headers = headers

            source_task = str(metadata.get("task", "bimanual_unscrew_cap"))
            task_text = task_to_text(source_task, args.task_text)
            record = EpisodeRecord(
                source_dir=episode_dir.name,
                npz_path=str(npz_path),
                metadata_path=str(metadata_path),
                source_episode_index=(
                    int(metadata["episode_index"])
                    if isinstance(metadata.get("episode_index"), int)
                    else None
                ),
                reset_seed=(
                    int(metadata["reset_seed"])
                    if isinstance(metadata.get("reset_seed"), int)
                    else None
                ),
                source_task=source_task,
                task_text=task_text,
                success=success,
                raw_frames=raw_frames,
                converted_frames=converted_frames,
            )
            records.append(record)
            print(
                f"[valid] {episode_dir.name}: raw={raw_frames}, "
                f"converted={converted_frames}, success={success}, task={source_task}"
            )
            if args.max_episodes is not None and len(records) >= args.max_episodes:
                break

        except ConversionError as exc:
            if args.skip_invalid:
                print(f"[skip-invalid] {exc}", file=sys.stderr)
                continue
            raise

    if not records:
        raise ConversionError("No valid episodes remain after filtering.")
    assert inferred_fps is not None

    if resize is not None:
        h, w = resize
        for camera in cameras:
            old = reference_headers[camera]
            reference_headers[camera] = ArrayHeader(
                shape=(old.shape[0], h, w, old.shape[-1]),
                dtype=old.dtype,
                fortran_order=False,
            )

    return records, reference_headers, inferred_fps


def build_features(
    args: argparse.Namespace,
    cameras: tuple[str, ...],
    headers: dict[str, ArrayHeader],
) -> dict[str, dict[str, Any]]:
    state_dim = headers[args.state_key].shape[1]
    action_dim = headers[args.action_key].shape[1]
    features: dict[str, dict[str, Any]] = {
        "observation.state": {
            "dtype": "float32",
            "shape": (state_dim,),
            "names": [f"{args.state_key}_{index:02d}" for index in range(state_dim)],
        },
        "action": {
            "dtype": "float32",
            "shape": (action_dim,),
            "names": [f"action_{index:02d}" for index in range(action_dim)],
        },
    }
    for source_key in cameras:
        _, height, width, channels = headers[source_key].shape
        features[output_camera_key(source_key)] = {
            "dtype": "video",
            "shape": (height, width, channels),
            "names": ["height", "width", "channel"],
        }
    return features


def stage_camera_arrays(
    npz: np.lib.npyio.NpzFile,
    cameras: tuple[str, ...],
    temporary_dir: Path,
) -> dict[str, np.ndarray]:
    arrays: dict[str, np.ndarray] = {}
    for key in cameras:
        print(f"    staging {key} ...")
        array = np.asarray(npz[key])
        stage_path = temporary_dir / f"{key}.npy"
        np.save(stage_path, array, allow_pickle=False)
        del array
        gc.collect()
        arrays[key] = np.load(stage_path, mmap_mode="r", allow_pickle=False)
    return arrays


def maybe_resize(image: np.ndarray, resize: tuple[int, int] | None) -> np.ndarray:
    if resize is None:
        return np.asarray(image)
    import cv2

    height, width = resize
    resized = cv2.resize(
        np.asarray(image),
        (width, height),
        interpolation=cv2.INTER_AREA,
    )
    if resized.ndim == 2:
        resized = resized[..., None]
    return np.asarray(resized, dtype=np.uint8)


def write_source_metadata(
    output_root: Path,
    destination_episode_index: int,
    record: EpisodeRecord,
) -> None:
    destination = (
        output_root
        / "source_metadata"
        / f"episode_{destination_episode_index:06d}_{record.source_dir}.json"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(record.metadata_path, destination)


def ensure_lerobot_version() -> str:
    try:
        version = importlib.metadata.version("lerobot")
    except importlib.metadata.PackageNotFoundError as exc:
        raise ConversionError(
            "LeRobot is not installed. Activate autolabsim-act and install lerobot==0.4.4."
        ) from exc
    if version != "0.4.4":
        print(
            f"[warning] Script targets LeRobot 0.4.4, but installed version is {version}.",
            file=sys.stderr,
        )
    return version


def print_scan_summary(
    records: list[EpisodeRecord],
    headers: dict[str, ArrayHeader],
    args: argparse.Namespace,
    cameras: tuple[str, ...],
    fps: int,
) -> None:
    total_raw = sum(record.raw_frames for record in records)
    total_converted = sum(record.converted_frames for record in records)
    print("\n=== Scan summary ===")
    print(f"Input root       : {args.input_root}")
    print(f"Episodes         : {len(records)}")
    print(f"Raw frames       : {total_raw}")
    print(f"Converted frames : {total_converted}")
    print(f"FPS              : {fps}")
    print(f"State            : {args.state_key} {headers[args.state_key].shape[1:]}")
    print(f"Action           : {args.action_key} {headers[args.action_key].shape[1:]}")
    print(f"Action offset    : {args.action_offset}")
    for camera in cameras:
        print(f"Camera           : {camera} {headers[camera].shape[1:]}")


def convert(args: argparse.Namespace) -> None:
    cameras = parse_cameras(args.cameras)
    resize = validate_resize(args)
    args.input_root = args.input_root.expanduser().resolve()
    args.output_root = args.output_root.expanduser().resolve()

    records, headers, fps = scan_episodes(args, cameras, resize)
    print_scan_summary(records, headers, args, cameras, fps)
    if args.dry_run:
        print("\nDry run complete; no files were written.")
        return

    lerobot_version = ensure_lerobot_version()
    from lerobot.datasets.lerobot_dataset import LeRobotDataset

    if args.output_root.exists():
        if not args.overwrite:
            raise ConversionError(
                f"Output already exists: {args.output_root}. Use --overwrite to replace it."
            )
        print(f"[overwrite] Removing {args.output_root}")
        shutil.rmtree(args.output_root)
    args.output_root.parent.mkdir(parents=True, exist_ok=True)

    temp_root = (
        args.temp_root.expanduser().resolve()
        if args.temp_root is not None
        else args.output_root.parent / ".autolabsim_lerobot_tmp"
    )
    temp_root.mkdir(parents=True, exist_ok=True)

    features = build_features(args, cameras, headers)
    print("\nCreating LeRobot dataset ...")
    dataset = LeRobotDataset.create(
        repo_id=args.repo_id,
        fps=fps,
        features=features,
        root=args.output_root,
        robot_type=args.robot_type,
        use_videos=True,
        image_writer_processes=0,
        image_writer_threads=max(0, args.image_writer_threads),
        batch_encoding_size=1,
        vcodec=args.vcodec,
    )

    manifest_episodes: list[dict[str, Any]] = []
    conversion_failed = False
    try:
        for destination_index, record in enumerate(records):
            print(
                f"\n[{destination_index + 1}/{len(records)}] "
                f"Converting {record.source_dir} ({record.converted_frames} frames)"
            )
            npz_path = Path(record.npz_path)
            with tempfile.TemporaryDirectory(
                prefix=f"{record.source_dir}_", dir=temp_root
            ) as temp_dir_name:
                temp_dir = Path(temp_dir_name)
                with np.load(npz_path, allow_pickle=False) as npz:
                    state = np.asarray(npz[args.state_key], dtype=np.float32)
                    actions = np.asarray(npz[args.action_key], dtype=np.float32)

                    if not np.isfinite(state).all():
                        raise ConversionError(f"{npz_path}: state contains NaN or Inf")
                    if not np.isfinite(actions).all():
                        raise ConversionError(f"{npz_path}: action contains NaN or Inf")

                    if args.in_memory:
                        camera_arrays = {
                            key: np.asarray(npz[key], dtype=np.uint8) for key in cameras
                        }
                    else:
                        camera_arrays = stage_camera_arrays(npz, cameras, temp_dir)

                    for t in range(record.converted_frames):
                        frame: dict[str, Any] = {
                            "observation.state": state[t],
                            "action": actions[t + args.action_offset],
                            "task": record.task_text,
                        }
                        for source_key in cameras:
                            frame[output_camera_key(source_key)] = maybe_resize(
                                camera_arrays[source_key][t], resize
                            )
                        dataset.add_frame(frame)

                dataset.save_episode(
                    parallel_encoding=not args.no_parallel_encoding
                )
                write_source_metadata(args.output_root, destination_index, record)
                episode_manifest = asdict(record)
                episode_manifest["destination_episode_index"] = destination_index
                manifest_episodes.append(episode_manifest)
                print(f"    saved destination episode {destination_index}")

                del state, actions, camera_arrays
                gc.collect()

    except Exception:
        conversion_failed = True
        raise
    finally:
        # finalize() is required in v0.4.4 to close Parquet footers.
        dataset.finalize()
        if conversion_failed:
            print(
                f"\n[warning] Conversion stopped early. Partial output remains at "
                f"{args.output_root}",
                file=sys.stderr,
            )

    manifest = {
        "format": "autolabsim_to_lerobot_act",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "lerobot_version": lerobot_version,
        "repo_id": args.repo_id,
        "robot_type": args.robot_type,
        "input_root": str(args.input_root),
        "output_root": str(args.output_root),
        "fps": fps,
        "state_key": args.state_key,
        "action_key": args.action_key,
        "action_offset": args.action_offset,
        "camera_mapping": {
            key: output_camera_key(key) for key in cameras
        },
        "resize": (
            {"height": resize[0], "width": resize[1]} if resize else None
        ),
        "vcodec": args.vcodec,
        "total_episodes": len(manifest_episodes),
        "total_frames": sum(item["converted_frames"] for item in manifest_episodes),
        "episodes": manifest_episodes,
    }
    manifest_path = args.output_root / "conversion_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print("\nConversion complete.")
    print(f"Output   : {args.output_root}")
    print(f"Episodes : {len(manifest_episodes)}")
    print(f"Frames   : {manifest['total_frames']}")
    print(f"Manifest : {manifest_path}")

    if not args.skip_verify:
        print("\nReloading dataset for verification ...")
        verified = LeRobotDataset(
            repo_id=args.repo_id,
            root=args.output_root,
            video_backend="pyav",
        )
        if verified.num_episodes != len(manifest_episodes):
            raise ConversionError(
                f"Verification failed: episodes={verified.num_episodes}, "
                f"expected={len(manifest_episodes)}"
            )
        if len(verified) != manifest["total_frames"]:
            raise ConversionError(
                f"Verification failed: frames={len(verified)}, "
                f"expected={manifest['total_frames']}"
            )
        sample = verified[0]
        print(f"Verified episodes : {verified.num_episodes}")
        print(f"Verified frames   : {len(verified)}")
        for key in ("observation.state", "action", *features.keys()):
            if key in sample:
                value = sample[key]
                shape = tuple(value.shape) if hasattr(value, "shape") else None
                print(f"  {key}: shape={shape}, type={type(value).__name__}")
        print("Dataset verification passed.")


def main() -> int:
    args = parse_args()
    try:
        convert(args)
    except ConversionError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)
        return 130
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
